//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFT_Overlay {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class TFTOverlay : global::System.Configuration.ApplicationSettingsBase {
        
        private static TFTOverlay defaultInstance = ((TFTOverlay)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TFTOverlay())));
        
        public static TFTOverlay Default {
            get {
                return defaultInstance;
            }
        }
    }
}
